version: "3"
services:
  api-docs:
    container_name: journey-api-docs-service
    image: romanojha/journey-api-docs-service
    build:
      context: ./api-docs
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./api-docs/.env.production
