version: "3"
services:
  api-docs:
    container_name: journey-api-docs-service
    image: romanojha/journey-api-docs-service
    build:
      context: ./api-docs-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - docker.env

  main-proxy:
    container_name: journey-main-proxy
    image: romanojha/journey-temp-main-proxy
    build:
      context: ./temp-main-proxy
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - docker.env

  user-api-gateway:
    container_name: journey-user-api-gateway
    image: romanojha/journey-user-api-gateway
    build:
      context: ./user-api-gateway
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - docker.env

  user-service:
    container_name: journey-user-service
    image: romanojha/journey-user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - docker.env
    depends_on:
      - postgres

  postgres:
    container_name: journey-postgres-db
    image: postgres:14
    ports:
      - "5433:5432"
    env_file:
      - docker.env
    # environment:
    #   POSTGRES_DB: ${USER_SERVICE_DATABASE_NAME}
    #   POSTGRES_USER: ${USER_SERVICE_DATABASE_USER}
    #   POSTGRES_PASSWORD: ${USER_SERVICE_DATABASE_PASSWORD}
    volumes:
      - journey-user-service-data:/var/lib/postgresql

  # admin-client:
  #   container_name: journey-admin-client
  #   image: romanojha/journey-admin-client
  #   build:
  #     context: ./admin-client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./admin-client/.env

  admin-service:
    container_name: journey-admin-service
    image: romanojha/journey-admin-service
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - docker.env

volumes:
  journey-user-service-data:
    driver: local
