version: "3"
services:
  api-docs:
    container_name: journey-api-docs-service
    image: romanojha/journey-api-docs-service
    build:
      context: ./api-docs-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

  main-proxy:
    container_name: journey-main-proxy
    image: roman-ojha/journey-temp-main-proxy
    build:
      context: ./temp-main-proxy
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.dev
