version: "3.9"
services:
  api-docs:
    container_name: journey-api-docs-service
    image: romanojha/journey-api-docs-service
    build:
      context: ./api-docs-service
      dockerfile: Dockerfile
    env_file:
      - docker.env

  main-proxy:
    container_name: journey-main-proxy
    image: romanojha/journey-temp-main-proxy
    build:
      context: ./temp-main-proxy
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - docker.env
    depends_on:
      - admin-service
      - api-gateway
      - api-docs

  api-gateway:
    container_name: journey-api-gateway
    image: romanojha/journey-api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - docker.env
    depends_on:
      - postgres
      - mysql

  user-service:
    container_name: journey-user-service
    image: romanojha/journey-user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - docker.env
    depends_on:
      - postgres

  user-service-prisma-studio:
    container_name: journey-user-service-prisma-studio
    image: romanojha/journey-user-service-prisma-studio
    build:
      context: ./user-service
      dockerfile: Prisma.Dockerfile
    env_file:
      - docker.env
    ports:
      - "5555:5555"
    depends_on:
      - user-service
      - postgres

  # admin-client:
  #   container_name: journey-admin-client
  #   image: romanojha/journey-admin-client
  #   build:
  #     context: ./admin-client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./admin-client/.env

  admin-service:
    container_name: journey-admin-service
    image: romanojha/journey-admin-service
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    env_file:
      - docker.env
    depends_on:
      - mysql

  merchant-service:
    container_name: journey-merchant-service
    image: romanojha/journey-merchant-service
    build:
      context: ./merchant-service
      dockerfile: Dockerfile
    # restart: unless-stopped
    volumes:
      - ./merchant-service:/var/www/html
    env_file:
      - ./merchant-service/docker.env
    depends_on:
      - mysql

  phpmyadmin:
    container_name: journey-phpmyadmin
    image: phpmyadmin:5.2.1-apache
    ports:
      - "8080:80"
    env_file:
      - docker.env
    links:
      - "mysql:db"

  postgres:
    container_name: journey-postgres-db
    image: postgres:14
    env_file:
      - docker.env
    # ports:
    #   - "5432:5432"
    volumes:
      - journey-postgresql:/var/lib/postgresql/data

  mysql:
    container_name: journey-mysql-db
    image: mysql:8.2.0
    env_file:
      - docker.env
    # ports:
    #   - "3306:3306"
    volumes:
      - journey-mysql:/var/lib/mysql

volumes:
  journey-postgresql:
    driver: local
  journey-mysql:
    driver: local
