openapi: 3.0.0
info:
  title: "Application API Docs"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000/api"
paths:
  /user/auth/register:
    post:
      summary: User registration
      description: Register a new user.
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "roman@gmail.com"
              password: "roman123"
              c_password: "roman123"
              gender: "MALE"
              number: 9843124323
              f_name: "Roman"
              l_name: "Ojha"
      responses:
        "201":
          description: User Registered Successfully
          content:
            application/json:
              example:
                status: true
                data:
                  id: 1
                  username: "<username>"
                  email: "<email>"
                  f_name: "<f_name>"
                  l_name: "<l_name>"
                  gender: "<gender>"
        "422":
          description: Validation Error
          content:
            application/json:
              example:
                message: "The given data was invalid"
                errors:
                  email: ["<error_message>"]
                  password: ["<error_message>"]
                  c_password: ["<error_message>"]
                  gender: ["<error_message>"]
                  number: ["<error_message>"]
                  f_name: ["<error_message"]
                  l_name: ["<error_message>"]
  # /user:
  #   get:
  #     summary: Get user information
  #     description: Retrieve information about a user.
  #     responses:
  #       "200":
  #         description: Successful response
  #         content:
  #           application/json:
  #             example:
  #               id: 1
  #               username: "john_doe"
  #               email: "john@example.com"

  # /login:
  #   post:
  #     summary: User login
  #     description: Log in a user.
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           example:
  #             username: "john_doe"
  #             password: "secure_password"
  #     responses:
  #       "200":
  #         description: Successful login
  #         content:
  #           application/json:
  #             example:
  #               token: "jwt_token"

  # /post:
  #   get:
  #     summary: Get posts
  #     description: Retrieve a list of posts.
  #     responses:
  #       "200":
  #         description: Successful response
  #         content:
  #           application/json:
  #             example:
  #               - id: 1
  #                 title: "First Post"
  #                 content: "This is the content of the first post."
  #               - id: 2
  #                 title: "Second Post"
  #                 content: "This is the content of the second post."

  # /comment:
  #   post:
  #     summary: Add a comment
  #     description: Add a comment to a post.
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           example:
  #             postId: 1
  #             text: "Great post!"
  #     responses:
  #       "201":
  #         description: Comment added successfully
  #         content:
  #           application/json:
  #             example:
  #               id: 1
  #               postId: 1
  #               text: "Great post!"
