apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-api-gateway
  namespace: journey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journey-api-gateway
  template:
    metadata:
      labels:
        app: journey-api-gateway
    spec:
      containers:
        - name: journey-api-gateway
          image: romanojha/journey-api-gateway
          envFrom:
            - configMapRef:
                name: journey-project-configmap
            - secretRef:
                name: journey-project-secret
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: journey-api-gateway
  namespace: journey
spec:
  selector:
    app: journey-api-gateway
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
