apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-merchant-service
  namespace: journey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journey-merchant-service
  template:
    metadata:
      labels:
        app: journey-merchant-service
    spec:
      containers:
        - name: journey-merchant-service
          image: romanojha/journey-merchant-service
          envFrom:
            - configMapRef:
                name: journey-project-configmap
            - configMapRef:
                name: journey-merchant-service-configmap
            - secretRef:
                name: journey-project-secret
            - secretRef:
                name: journey-merchant-service-secret
          resources: # research on this one about required resources
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: journey-merchant-service
  namespace: journey
spec:
  selector:
    app: journey-merchant-service
  type: ClusterIP
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: journey-merchant-service-configmap
  namespace: journey
data:
  APP_NAME: Journey
  APP_ENV: local
  APP_DEBUG: "true"
  APP_URL: http://localhost
  SERVER_PORT: "8005"
  SERVER_HOST: 0.0.0.0
  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug
  DB_CONNECTION: mysql
  DB_HOST: journey-mysql
  DB_PORT: "3306"
  DB_DATABASE: journey_merchant_service
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
  MEMCACHED_HOST: 127.0.0.1
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: "6379"
  MAIL_MAILER: smtp
  MAIL_HOST: mailpit
  MAIL_PORT: "1025"
  MAIL_FROM_NAME: "${APP_NAME}"
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  PUSHER_HOST: ""
  PUSHER_PORT: "443"
  PUSHER_SCHEME: https
  PUSHER_APP_CLUSTER: mt1
  VITE_APP_NAME: "${APP_NAME}"
  VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  VITE_PUSHER_HOST: "${PUSHER_HOST}"
  VITE_PUSHER_PORT: "${PUSHER_PORT}"
  VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
  VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
  # JWT valid for 43200 minute = 30 days
  JWT_TTL: "43200"
