#	Copyright 2016, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Reference: https://www.cloudskillsboost.google/focuses/640?parent=catalog
---
apiVersion: v1
kind: Service
metadata:
  name: journey-mongo
  namespace: journey
  labels:
    name: journey-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: journey-mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: journey-mongo
  namespace: journey
spec:
  serviceName: "journey-mongo"
  replicas: 3
  selector:
    matchLabels:
      role: journey-mongo
  template:
    metadata:
      labels:
        role: journey-mongo
        environment: preview
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: journey-mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: journey-mongo-persistent-storage
              mountPath: /data/db
        - name: journey-mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=journey-mongo,environment=preview"
  volumeClaimTemplates:
    - metadata:
        name: journey-mongo-persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "fast"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
