apiVersion: v1
kind: ConfigMap
metadata:
  name: journey-project-configmap
  namespace: journey
data:
  ENVIRONMENT: k8s
  POSTGRES_DB: postgres
  MAIN_PROXY_PORT: "8003"
  MAIN_PROXY_URL: http://journey-main-proxy:8003 # It needs to be External Ip address of the service
  API_DOCS_SERVICE_PORT: "8000"
  API_DOCS_SERVICE_URL: http://journey-api-docs-service:8000 # need to change
  ADMIN_SERVICE_PORT: "8004"
  ADMIN_SERVICE_URL: http://journey-admin-service:8004 # need to change
  ADMIN_SERVICE_DATABASE_NAME: journey_admin_service
  ADMIN_SERVICE_DATABASE_HOST: journey-mysql
  ADMIN_SERVICE_DATABASE_PORT: "3306"
  ADMIN_CLIENT_PORT: "3000"
  ADMIN_CLIENT_URL: http://localhost:3000 # need to change
  MERCHANT_SERVICE_PORT: "8005"
  MERCHANT_SERVICE_URL: http://journey-merchant-service:8005 # need to change
  MERCHANT_SERVICE_DATABASE_NAME: journey_merchant_service
  MERCHANT_SERVICE_DATABASE_HOST: journey-mysql
  MERCHANT_SERVICE_DATABASE_PORT: "3306"
  API_GATEWAY_PORT: "8001"
  API_GATEWAY_URL: http://journey-api-gateway:8001 # need to change
  USER_SERVICE_PORT: "8002"
  USER_SERVICE_URL: http://journey-user-service:8002 # need to change
  USER_SERVICE_PRISMA_STUDIO_URL: http://localhost:5555 # need to change
  USER_SERVICE_PRISMA_STUDIO_PORT: "5555"
  user_service_database_name: "journey-user-service"
