apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-temp-main-proxy
  namespace: journey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: journey-temp-main-proxy
  template:
    metadata:
      labels:
        app: journey-temp-main-proxy
    spec:
      containers:
        - name: journey-temp-main-proxy
          image: romanojha/journey-temp-main-proxy
          envFrom:
            - configMapRef:
                name: journey-project-configmap
            - secretRef:
                name: journey-project-secret
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: journey-temp-main-proxy
  namespace: journey
spec:
  selector:
    app: journey-temp-main-proxy
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
      nodePort: 30003
