apiVersion: v1
kind: Secret
metadata:
  name: journey-project-secret
  namespace: journey
type: Opaque
stringData:
  SWAGGER_AUTH_TOKEN: <swagger_auth_token>
  PROJECT_PUBLIC_KEY: |
    "-----BEGIN RSA PUBLIC KEY----- 
    public key 
    -----END RSA PUBLIC KEY-----"
  PROJECT_PRIVATE_KEY: |
    "-----BEGIN RSA PRIVATE KEY----- 
    private key 
    -----END RSA PRIVATE KEY-----"
  GCP_CLOUD_STORAGE_PUBLIC_BUCKET_NAME: gcp-storage-bucket-name
  POSTGRES_USER: <user_name>
  POSTGRES_PASSWORD: <password>
  MYSQL_ROOT_PASSWORD: <password>
  ADMIN_SERVICE_SECRET: <secret_key>
  ADMIN_SERVICE_DATABASE_USER: <user>
  ADMIN_SERVICE_DATABASE_PASSWORD: <password>
  MERCHANT_SERVICE_DATABASE_USER: <user>
  MERCHANT_SERVICE_DATABASE_PASSWORD: "<password>"
  MERCHANT_SERVICE_JWT_SECRET_KEY: <Jwt_secret_key>
  USER_SERVICE_DATABASE_URL: "postgresql://<user>:<password>@journey-postgresql:5432/journey-user-service"
  MERCHANT_V_AND_T_SERVICE_DATABASE_URL: "mongodb+srv://<user>:<password>@cluster0.ab1cd.mongodb.net/merchant_v_and_t_service?retryWrites=true&w=majority"
  MERCHANT_V_AND_T_SERVICE_DATABASE_USERNAME: "<user>"
  MERCHANT_V_AND_T_SERVICE_DATABASE_PASSWORD: "<password>"
  KHALTI_LIVE_SECRET_KEY: "Key xyz"
  KHALTI_PUBLIC_KEY: "xyz"
  KHALTI_TEST_SECRET_KEY: "test_secret_key_xyz"
  KHALTI_TEST_PUBLIC_KEY: "test_public_key_xyz"
  KHALTI_PAYMENT_BASE_URL: "https://a.khalti.com/api/v2"
  CLOUD_AMQP_INSTANCE_URL: "amqps://xyz:zyx@xyz.com/xyz"
