# Generated by Django 4.2.7 on 2023-11-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
