# Generated by Django 4.2.7 on 2023-11-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_admin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
