name: Build and Push Microservice Images on Docker Registries
on:
  push:
    branches:
      - "main"
jobs:
  build-push-docker-images:
    name: Build Docker Images and Push into Docker Hub
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: roman-personal-398809
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker compose -f docker-compose.prod.yml build

      - name: Push image to DO Container Registry
        run: docker compose -f docker-compose.prod.yml push
