name: Deploy Project Into Kubernetes Clusters
on:
  workflow_run:
    workflows: ["Build and Push Applications Images on Docker Registries"]
    types:
      - completed

jobs:
  deploy-to-gke:
    name: Deploy Project Into Google Kubernetes Engine(GKE)
    runs-on: ubuntu-latest
    # needs: build-push-docker-images
    env:
      GCP_PROJECT_ID: roman-personal-398809
      GKE_CLUSTER_NAME: autopilot-cluster-1
      GKE_CLUSTER_ZONE: asia-south1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: "Auth Google Cloud SDK"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}"
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure kubectl
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --region=${{ env.GKE_CLUSTER_ZONE }}

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f ./manifests
          kubectl delete pods --all -n default
