name: (Staging) Build and Push Microservice Images on Docker Registries
on:
  push:
    branches:
      - "staging"
jobs:
  build-push-docker-images:
    name: Build Docker Images and Push into Docker Hub
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: roman-personal-398809
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build Admin Client Project
      #   run: |
      #     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      #     export NVM_DIR="$HOME/.nvm"
      #     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      #     [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      #     nvm install 16.5.0
      #     nvm use 16.5.0
      #     cd ./admin-client
      #     corepack enable
      #     yarn install
      #     yarn build

      - name: Build image
        run: |
          npm install -g yarn
          yarn install
          yarn docker-build:prod

      - name: Push image to DO Container Registry
        run: docker compose -f docker-compose.prod.yml push
